headersOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\User\\Downloads\\eco_ref_model-main (1)\\eco_ref_model-main\\web"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "*.html"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "*.css"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "*.js"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "*.png"

[headers.values]
Cache-Control = "public, max-age=2592000"

[[redirects]]
from = "/"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]