# 모델 피처 원본 코드 -> 한글 설명 매핑.
# JEMU_* 부분은 eda_pipeline/step4_borrower_sheet.py의 JEMU_COL_MAP과 동일.
# 그 외는 docs/데이터명세서.md 및 eda_pipeline 주석에서 확인 가능한 범위까지 매핑.
# 매핑이 없는 피처는 원본 코드명을 그대로 노출한다 (임의로 지어내지 않음).
# ※ 아래 매핑은 input/가상사업자_JEMU_재무데이터v.txt 0행(한글 논리명)을 직접 대조해
#   정정한 것이다. 과거 매핑은 118100 부터 한 칸씩 밀려 28개 중 21개가 틀려 있었다.
#   (예: 191204 를 'ROE' 로, 191208 을 '매출채권회전율' 로 표기)
#   표시 라벨만 바로잡았으며 계산 로직은 원천 헤더와 이미 일치하므로 손대지 않았다.
FEATURE_LABELS: dict[str, str] = {
    # JEMU_* 재무 계정 (eda_pipeline/step4_borrower_sheet.py JEMU_COL_MAP)
    "JEMU_112000": "유동자산(계)",
    "JEMU_114000": "비유동자산(계)",
    "JEMU_115000": "자산총계",
    "JEMU_116000": "유동부채(계)",
    "JEMU_117000": "비유동부채(계)",
    "JEMU_118000": "부채총계",
    "JEMU_118100": "자본금",
    "JEMU_118900": "자본총계",
    "JEMU_121000": "매출액",
    "JEMU_123000": "매출총이익(손실)",
    "JEMU_125000": "영업이익(손실)",
    "JEMU_125100": "영업외수익",
    "JEMU_126000": "영업외비용",
    "JEMU_128000": "법인세비용차감전계속사업이익(손실)",
    "JEMU_129000": "당기순이익(손실)",
    "JEMU_191104": "매출액증가율",
    "JEMU_191105": "순이익증가율",
    "JEMU_191108": "영업이익증가율",
    "JEMU_191110": "재고자산증가율",
    "JEMU_191204": "매출액영업이익율",
    "JEMU_191207": "이자보상배율(배)",
    "JEMU_191208": "자기자본순이익율",
    "JEMU_191210": "총자본순이익율",
    "JEMU_191310": "EBITDA이자보상배율(배)",
    "JEMU_191502": "매출채권회전율",
    "JEMU_191503": "영업자산회전율",
    "JEMU_191505": "재고자산회전율",
    "JEMU_191506": "총자본회전율",

    # 기업 기본 정보 / 신용평가사 지표 (데이터명세서.md)
    "COPR_OPNP_C": "기업공개구분",
    "STD_INDS_CFC": "표준산업분류코드(업종)",
    "BUSINESS_AGE": "업력",
    "CG01_KIS_SCORE": "나이스(KIS) 신용평점",
    "C302_CRI_ORD": "나이스 CRI 신용등급",
    "AA10_PERS_CNT": "종업원 수",
    "AA17_TOT_SEL_AM": "총판매(매출) 금액",
    "AA17_LA_XPO_AM": "외화 익스포저 금액",
    "AA17_DME_AM": "국내 매출 금액",
    "AA17_EXT_PROD_RECORD_YN": "수출 실적 여부",

    # 관찰/여신 등급 (OBV)
    "OBV_ELYWRN_OBV_GRD_DSC": "조기경보 관찰 등급",
    "OBV_LN_LMT_AM": "여신 한도 금액",
    "OBV_LN_BAC": "여신 잔액",
    "OBV_LN_LMT_BAC": "여신 한도 잔액",
    "OBV_BZL_RZVL_ASP_ELGD": "사업자 회수예상 적격등급",
    "OBV_LD_AM": "대출 금액",
    "OBV_XPC_LSS_AM": "예상 손실 금액",

    # 신용조회기관(CRIF) 연체/신용불량 이력
    "CRIF_CRDBD_RSNC": "신용불량 사유 코드",
    "CRIF_SUM(CRDBD_RSN_AM)": "신용불량 발생 금액 합계",
    "CRIF_SUM(CRDBD_OVD_AM)": "연체 금액 합계",
    "CRIF_MAX(CRDBD_RLS_RSNC)": "신용불량 해제 사유(최근)",

    # 외화 익스포저(AC12)
    "AC12_US_FC_AM": "달러화 외화표시 익스포저",
    "AC12_US_KRW_AM": "달러화 원화환산 익스포저",
    "AC12_JP_FC_AM": "엔화 외화표시 익스포저",
    "AC12_JP_KRW_AM": "엔화 원화환산 익스포저",
    "AC12_CN_FC_AM": "위안화 외화표시 익스포저",
    "AC12_CN_KRW_AM": "위안화 원화환산 익스포저",
    "AC12_EU_FC_AM": "유로화 외화표시 익스포저",
    "AC12_EU_KRW_AM": "유로화 원화환산 익스포저",
    "AC12_TOTAL_KRW_AM": "외화 익스포저 총액(원화환산)",
    "AC12_EXT_OTHER_KRW_AM": "기타 외화 익스포저(원화환산)",

    # 거시경제 지표 (금리/환율/물가/유가/증시/경기)
    "base_rate_diff12": "기준금리 12개월 변동",
    "call_rate_overnight_diff12": "콜금리 12개월 변동",
    "KORIBOR_12m_diff12": "코리보(12M) 변동",
    "KORIBOR_6m_diff12": "코리보(6M) 변동",
    "KORIBOR_3m_diff12": "코리보(3M) 변동",
    "corporate_bond_3y_AA_diff12": "회사채(3년 AA) 금리 변동",
    "treasury_bond_10y_diff12": "국고채 10년물 금리 변동",
    "treasury_bond_1y_diff12": "국고채 1년물 금리 변동",
    "US_3M_tbill_diff12": "미국 13주 재정증권 금리 변동",
    "US_10Y_treasury_diff12": "미국채 10년물 금리 변동",
    "USD_KRW_log_ret": "원/달러 환율 변동률",
    "EUR_KRW_vol_m": "원/유로 환율 변동성",
    "JPY_KRW_vol_m": "원/엔 환율 변동성",
    "DXY_dollar_index_log_ret": "달러인덱스 변동률",
    "CPI_core_yoy": "근원 소비자물가 상승률",
    "CPI_core_excl_food_energy_yoy": "식품·에너지 제외 근원물가 상승률",
    "CPI_food_nonalcohol_yoy": "식품물가 상승률",
    "brent_crude_oil_log_ret": "브렌트유 가격 변동률",
    "WTI_crude_oil_log_ret": "WTI유 가격 변동률",
    "KOSPI_log_ret": "코스피 수익률",
    "KOSDAQ_log_ret_ma3m": "코스닥 수익률(3개월 평균)",
    "VIX_vol_m": "VIX 변동성 지수",
    "BSI_mfg_export_yoy": "제조업 수출 기업경기실사지수",
    "BSI_mfg_domestic_yoy": "제조업 내수 기업경기실사지수",
    "import_index_yoy": "수입물가지수 증가율",

    # ── [2026-09-02] gain 상위 15 에 등장하는데 라벨이 없던 7건 (승인 후 추가) ──
    #   JEMU 3건은 input/가상사업자_JEMU_재무데이터v.txt 0/1행(정본)을 직접 대조했다.
    #   한 칸 밀림 사고를 겪은 부분이라 추측하지 않고 원천을 확인했다.
    #   _val 접미사는 sentinel 을 제외한 연속값이라는 뜻이지만, 라벨에 그 설명을
    #   넣으면 화면에서 길어져 가독성이 떨어진다. 정의는 문서에서 설명한다.
    "JEMU_191310_val": "EBITDA이자보상배율",
    "JEMU_191502_val": "매출채권회전율",
    "JEMU_191503_val": "영업자산회전율",
    "STD_INDS_MID2": "업종 중분류",
    "STD_INDS_SECTION": "업종 대분류",
    #   원천 대응이 없는 파생 2건. "결측" 이 아니라 "평가 이력 없음" 이 의미상 정확하다
    #   — A6 분해에서 이 변수가 이력 유무 정보를 담는 것으로 확인됐다.
    "C302_MISSING_YN": "외부신용평가 이력 없음",
    "JEMU_asset_turnover_avg": "총자산회전율(평균잔액 기준)",
}


# ── [2026-09-03] 거시 변환 변수·상호작용항 라벨 (자동 생성) ──────────────
#   생성기: eda_pipeline/step41_macro_labels.py
#   원천: api_data_processing/config/indicator_names.csv 의 series_name->name_kr
#   ★ 수동 하드코딩하지 않는다. 원천에 없는 지표는 라벨을 만들지 않고
#     원본 코드명을 그대로 노출한다 (JEMU 한 칸 밀림 사고의 교훈).
MACRO_FEATURE_LABELS: dict[str, str] = {
    "BSI_mfg_biz_yoy": "제조업 업황BSI 전년동월대비",
    "BSI_mfg_biz_yoy_ma3m": "제조업 업황BSI 전년동월대비 3개월 이동평균",
    "BSI_mfg_domestic_yoy_ma3m": "제조업 내수BSI 전년동월대비 3개월 이동평균",
    "BSI_mfg_export_yoy_ma3m": "제조업 수출BSI 전년동월대비 3개월 이동평균",
    "BSI_nonmfg_biz_yoy": "비제조업 업황BSI 전년동월대비",
    "BSI_nonmfg_biz_yoy_ma3m": "비제조업 업황BSI 전년동월대비 3개월 이동평균",
    "CD_rate_91d_diff12": "CD 유통수익률 (91일) 12개월 차분",
    "CD_rate_91d_diff12_ma3m": "CD 유통수익률 (91일) 12개월 차분 3개월 이동평균",
    "CNY_KRW_log_ret": "원/위안 환율 (종가) 월간 로그수익률",
    "CNY_KRW_log_ret_ma3m": "원/위안 환율 (종가) 월간 로그수익률 3개월 이동평균",
    "CNY_KRW_vol_m": "원/위안 환율 (종가) 월간 변동성",
    "CNY_KRW_vol_m_ma3m": "원/위안 환율 (종가) 월간 변동성 3개월 이동평균",
    "CPI_core_excl_food_energy_yoy_ma3m": "소비자물가 근원물가 (식료품·에너지 제외) 전년동월대비 3개월 이동평균",
    "CPI_core_yoy_ma3m": "소비자물가 근원물가지수 전년동월대비 3개월 이동평균",
    "CPI_food_nonalcohol_yoy_ma3m": "소비자물가 식료품·비주류음료 전년동월대비 3개월 이동평균",
    "CP_91d_log_ret": "CP 금리 (91일) 월간 로그수익률",
    "CP_91d_log_ret_ma3m": "CP 금리 (91일) 월간 로그수익률 3개월 이동평균",
    "CP_91d_vol_m": "CP 금리 (91일) 월간 변동성",
    "CP_91d_vol_m_ma3m": "CP 금리 (91일) 월간 변동성 3개월 이동평균",
    "CSI_composite_yoy": "소비자심리지수(CCSI) 전년동월대비",
    "CSI_composite_yoy_ma3m": "소비자심리지수(CCSI) 전년동월대비 3개월 이동평균",
    "CSI_living_prospect_yoy": "생활형편전망CSI 전년동월대비",
    "CSI_living_prospect_yoy_ma3m": "생활형편전망CSI 전년동월대비 3개월 이동평균",
    "DXY_dollar_index_log_ret_ma3m": "달러 인덱스 (DXY) 월간 로그수익률 3개월 이동평균",
    "DXY_dollar_index_vol_m": "달러 인덱스 (DXY) 월간 변동성",
    "DXY_dollar_index_vol_m_ma3m": "달러 인덱스 (DXY) 월간 변동성 3개월 이동평균",
    "DowJones_log_ret": "다우존스 산업평균지수 월간 로그수익률",
    "DowJones_log_ret_ma3m": "다우존스 산업평균지수 월간 로그수익률 3개월 이동평균",
    "DowJones_vol_m": "다우존스 산업평균지수 월간 변동성",
    "DowJones_vol_m_ma3m": "다우존스 산업평균지수 월간 변동성 3개월 이동평균",
    "EUR_KRW_log_ret": "원/유로 환율 월간 로그수익률",
    "EUR_KRW_log_ret_ma3m": "원/유로 환율 월간 로그수익률 3개월 이동평균",
    "EUR_KRW_vol_m_ma3m": "원/유로 환율 월간 변동성 3개월 이동평균",
    "JPY_KRW_log_ret": "원/엔 환율 월간 로그수익률",
    "JPY_KRW_log_ret_ma3m": "원/엔 환율 월간 로그수익률 3개월 이동평균",
    "JPY_KRW_vol_m_ma3m": "원/엔 환율 월간 변동성 3개월 이동평균",
    "KORIBOR_12m_diff12_ma3m": "KORIBOR (12개월) 12개월 차분 3개월 이동평균",
    "KORIBOR_3m_diff12_ma3m": "KORIBOR (3개월) 12개월 차분 3개월 이동평균",
    "KORIBOR_6m_diff12_ma3m": "KORIBOR (6개월) 12개월 차분 3개월 이동평균",
    "KOSDAQ_log_ret": "코스닥 종합지수 월간 로그수익률",
    "KOSDAQ_vol_m": "코스닥 종합지수 월간 변동성",
    "KOSDAQ_vol_m_ma3m": "코스닥 종합지수 월간 변동성 3개월 이동평균",
    "KOSPI_log_ret_ma3m": "코스피 종합지수 월간 로그수익률 3개월 이동평균",
    "KOSPI_vol_m": "코스피 종합지수 월간 변동성",
    "KOSPI_vol_m_ma3m": "코스피 종합지수 월간 변동성 3개월 이동평균",
    "Lf_liquidity_yoy": "Lf 금융기관유동성 전년동월대비",
    "Lf_liquidity_yoy_ma3m": "Lf 금융기관유동성 전년동월대비 3개월 이동평균",
    "M1_narrow_money_yoy": "M1 협의통화 전년동월대비",
    "M1_narrow_money_yoy_ma3m": "M1 협의통화 전년동월대비 3개월 이동평균",
    "M2_broad_money_yoy": "M2 광의통화 (평잔) 전년동월대비",
    "M2_broad_money_yoy_ma3m": "M2 광의통화 (평잔) 전년동월대비 3개월 이동평균",
    "MSB_91d_log_ret": "통안증권 금리 (91일) 월간 로그수익률",
    "MSB_91d_log_ret_ma3m": "통안증권 금리 (91일) 월간 로그수익률 3개월 이동평균",
    "MSB_91d_vol_m": "통안증권 금리 (91일) 월간 변동성",
    "MSB_91d_vol_m_ma3m": "통안증권 금리 (91일) 월간 변동성 3개월 이동평균",
    "NASDAQ_log_ret": "나스닥 종합지수 월간 로그수익률",
    "NASDAQ_log_ret_ma3m": "나스닥 종합지수 월간 로그수익률 3개월 이동평균",
    "NASDAQ_vol_m": "나스닥 종합지수 월간 변동성",
    "NASDAQ_vol_m_ma3m": "나스닥 종합지수 월간 변동성 3개월 이동평균",
    "Nikkei225_log_ret": "닛케이 225 지수 월간 로그수익률",
    "Nikkei225_log_ret_ma3m": "닛케이 225 지수 월간 로그수익률 3개월 이동평균",
    "Nikkei225_vol_m": "닛케이 225 지수 월간 변동성",
    "Nikkei225_vol_m_ma3m": "닛케이 225 지수 월간 변동성 3개월 이동평균",
    "PPI_total_yoy": "생산자물가지수 (총지수) 전년동월대비",
    "PPI_total_yoy_ma3m": "생산자물가지수 (총지수) 전년동월대비 3개월 이동평균",
    "SP500_log_ret": "S&P 500 지수 월간 로그수익률",
    "SP500_log_ret_ma3m": "S&P 500 지수 월간 로그수익률 3개월 이동평균",
    "SP500_vol_m": "S&P 500 지수 월간 변동성",
    "SP500_vol_m_ma3m": "S&P 500 지수 월간 변동성 3개월 이동평균",
    "Shanghai_Composite_log_ret": "상해종합지수 월간 로그수익률",
    "Shanghai_Composite_log_ret_ma3m": "상해종합지수 월간 로그수익률 3개월 이동평균",
    "Shanghai_Composite_vol_m": "상해종합지수 월간 변동성",
    "Shanghai_Composite_vol_m_ma3m": "상해종합지수 월간 변동성 3개월 이동평균",
    "USD_KRW_log_ret_ma3m": "원/달러 환율 월간 로그수익률 3개월 이동평균",
    "USD_KRW_vol_m": "원/달러 환율 월간 변동성",
    "USD_KRW_vol_m_ma3m": "원/달러 환율 월간 변동성 3개월 이동평균",
    "US_10Y_treasury_diff12_ma3m": "미국 10년물 국채 수익률 12개월 차분 3개월 이동평균",
    "US_3M_tbill_diff12_ma3m": "미국 13주 재정증권 수익률 12개월 차분 3개월 이동평균",
    "VIX_log_ret": "VIX 변동성 지수 월간 로그수익률",
    "VIX_log_ret_ma3m": "VIX 변동성 지수 월간 로그수익률 3개월 이동평균",
    "VIX_vol_m_ma3m": "VIX 변동성 지수 월간 변동성 3개월 이동평균",
    "WTI_crude_oil_log_ret_ma3m": "WTI 원유 선물 월간 로그수익률 3개월 이동평균",
    "WTI_crude_oil_vol_m": "WTI 원유 선물 월간 변동성",
    "WTI_crude_oil_vol_m_ma3m": "WTI 원유 선물 월간 변동성 3개월 이동평균",
    "base_rate_diff12_ma3m": "한국은행 기준금리 12개월 차분 3개월 이동평균",
    "brent_crude_oil_log_ret_ma3m": "브렌트유 선물 월간 로그수익률 3개월 이동평균",
    "brent_crude_oil_vol_m": "브렌트유 선물 월간 변동성",
    "brent_crude_oil_vol_m_ma3m": "브렌트유 선물 월간 변동성 3개월 이동평균",
    "call_rate_overnight_brokered_diff12": "콜금리 (1일물 중개회사거래) 12개월 차분",
    "call_rate_overnight_brokered_diff12_ma3m": "콜금리 (1일물 중개회사거래) 12개월 차분 3개월 이동평균",
    "call_rate_overnight_diff12_ma3m": "콜금리 (1일물 전체거래) 12개월 차분 3개월 이동평균",
    "construction_cost_index_yoy": "건설공사비지수 전년동월대비",
    "construction_cost_index_yoy_ma3m": "건설공사비지수 전년동월대비 3개월 이동평균",
    "copper_log_ret": "구리 선물 월간 로그수익률",
    "copper_log_ret_ma3m": "구리 선물 월간 로그수익률 3개월 이동평균",
    "copper_vol_m": "구리 선물 월간 변동성",
    "copper_vol_m_ma3m": "구리 선물 월간 변동성 3개월 이동평균",
    "corn_log_ret": "옥수수 선물 월간 로그수익률",
    "corn_log_ret_ma3m": "옥수수 선물 월간 로그수익률 3개월 이동평균",
    "corn_vol_m": "옥수수 선물 월간 변동성",
    "corn_vol_m_ma3m": "옥수수 선물 월간 변동성 3개월 이동평균",
    "corporate_bond_3y_AA_diff12_ma3m": "회사채 수익률 (3년 AA-) 12개월 차분 3개월 이동평균",
    "credit_spread_diff12": "신용스프레드(회사채AA-3년 − 국고채3년) 12개월 차분",
    "credit_spread_diff12_ma3m": "신용스프레드(회사채AA-3년 − 국고채3년) 12개월 차분 3개월 이동평균",
    "current_account_quarterly_yoy": "경상수지 (분기별) 전년동월대비",
    "current_account_quarterly_yoy_ma3m": "경상수지 (분기별) 전년동월대비 3개월 이동평균",
    "current_account_yoy": "경상수지 (월별) 전년동월대비",
    "current_account_yoy_ma3m": "경상수지 (월별) 전년동월대비 3개월 이동평균",
    "export_index_yoy": "수출지수 전년동월대비",
    "export_index_yoy_ma3m": "수출지수 전년동월대비 3개월 이동평균",
    "export_price_index_KOR_yoy": "수출물가지수 (한국) 전년동월대비",
    "export_price_index_KOR_yoy_ma3m": "수출물가지수 (한국) 전년동월대비 3개월 이동평균",
    "gold_log_ret": "금 선물 월간 로그수익률",
    "gold_log_ret_ma3m": "금 선물 월간 로그수익률 3개월 이동평균",
    "gold_vol_m": "금 선물 월간 변동성",
    "gold_vol_m_ma3m": "금 선물 월간 변동성 3개월 이동평균",
    "goods_balance_yoy": "상품수지 전년동월대비",
    "goods_balance_yoy_ma3m": "상품수지 전년동월대비 3개월 이동평균",
    "household_credit_yoy": "가계신용 합계 전년동월대비",
    "household_credit_yoy_ma3m": "가계신용 합계 전년동월대비 3개월 이동평균",
    "household_loan_yoy": "가계대출 전년동월대비",
    "household_loan_yoy_ma3m": "가계대출 전년동월대비 3개월 이동평균",
    "housing_price_index_yoy": "주택가격지수 전년동월대비",
    "housing_price_index_yoy_ma3m": "주택가격지수 전년동월대비 3개월 이동평균",
    "import_index_yoy_ma3m": "수입지수 전년동월대비 3개월 이동평균",
    "ix_BSI_mfg_domestic__mfg": "제조업 내수BSI × 제조업 여부",
    "ix_CNY_KRW_ret__fx_hybrid": "원/위안 환율 (종가) 월간 로그수익률 × 수출비중(업종추정 병용)",
    "ix_CNY_KRW_vol__mfg": "원/위안 환율 (종가) 월간 변동성 × 제조업 여부",
    "ix_CPI_food_nonalcohol__rate": "소비자물가 식료품·비주류음료 × 차입금의존도",
    "ix_CSI_composite__young": "소비자심리지수(CCSI) × 업력 5년 이하",
    "ix_EUR_KRW_vol__mfg": "원/유로 환율 월간 변동성 × 제조업 여부",
    "ix_JPY_KRW_ret__mfg": "원/엔 환율 월간 로그수익률 × 제조업 여부",
    "ix_KORIBOR_spread_d12__liq": "단기금리스프레드(KORIBOR3M − 기준금리) 12개월 차분 × 단기부채비중",
    "ix_Shanghai_Composite_ret__mfg": "상해종합지수 월간 로그수익률 × 제조업 여부",
    "ix_current_account_quarterly__mfg": "경상수지 (분기별) × 제조업 여부",
    "ix_export_index__mfg": "수출지수 × 제조업 여부",
    "ix_gold_ret__inv": "금 선물 월간 로그수익률 × 재고부담",
    "ix_soybean_vol__inv": "대두 선물 월간 변동성 × 재고부담",
    "ix_unsold_housing__mfg": "미분양 주택수 × 제조업 여부",
    "liquidity_spread_diff12": "유동성스프레드(CP91일 − 통안91일) 12개월 차분",
    "liquidity_spread_diff12_ma3m": "유동성스프레드(CP91일 − 통안91일) 12개월 차분 3개월 이동평균",
    "monetary_base_sa_yoy": "본원통화 (계절조정 평잔) 전년동월대비",
    "monetary_base_sa_yoy_ma3m": "본원통화 (계절조정 평잔) 전년동월대비 3개월 이동평균",
    "natural_gas_log_ret": "천연가스 선물 월간 로그수익률",
    "natural_gas_log_ret_ma3m": "천연가스 선물 월간 로그수익률 3개월 이동평균",
    "natural_gas_vol_m": "천연가스 선물 월간 변동성",
    "natural_gas_vol_m_ma3m": "천연가스 선물 월간 변동성 3개월 이동평균",
    "silver_log_ret": "은 선물 월간 로그수익률",
    "silver_log_ret_ma3m": "은 선물 월간 로그수익률 3개월 이동평균",
    "silver_vol_m": "은 선물 월간 변동성",
    "silver_vol_m_ma3m": "은 선물 월간 변동성 3개월 이동평균",
    "soybean_log_ret": "대두 선물 월간 로그수익률",
    "soybean_log_ret_ma3m": "대두 선물 월간 로그수익률 3개월 이동평균",
    "soybean_vol_m": "대두 선물 월간 변동성",
    "soybean_vol_m_ma3m": "대두 선물 월간 변동성 3개월 이동평균",
    "treasury_bond_10y_diff12_ma3m": "국고채 수익률 (10년) 12개월 차분 3개월 이동평균",
    "treasury_bond_1y_diff12_ma3m": "국고채 수익률 (1년) 12개월 차분 3개월 이동평균",
    "treasury_bond_1y_monthly_diff12": "국고채 수익률 월평균 (1년) 12개월 차분",
    "treasury_bond_1y_monthly_diff12_ma3m": "국고채 수익률 월평균 (1년) 12개월 차분 3개월 이동평균",
    "treasury_bond_3y_diff12": "국고채 수익률 (3년) 12개월 차분",
    "treasury_bond_3y_diff12_ma3m": "국고채 수익률 (3년) 12개월 차분 3개월 이동평균",
    "treasury_bond_5y_diff12": "국고채 수익률 (5년) 12개월 차분",
    "treasury_bond_5y_diff12_ma3m": "국고채 수익률 (5년) 12개월 차분 3개월 이동평균",
    "unemployment_rate_yoy": "실업률 전년동월대비",
    "unemployment_rate_yoy_ma3m": "실업률 전년동월대비 3개월 이동평균",
    "unsold_housing_yoy": "미분양 주택수 전년동월대비",
    "unsold_housing_yoy_ma3m": "미분양 주택수 전년동월대비 3개월 이동평균",
}

FEATURE_LABELS.update(MACRO_FEATURE_LABELS)

def get_feature_label(code: str) -> str:
    return FEATURE_LABELS.get(code, code)
